version: '{build}' 
configuration:
- Release
platform: Any CPU 
image: Visual Studio 2017

environment: 
 DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0") 

install:
- choco install gitversion.portable -y

before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
- build -c Release

test_script:
- dotnet test src\dotnet-ildasm.tests\dotnet-ildasm.tests.csproj
- run-cross-checks.cmd

after_test:
- dotnet pack src\dotnet-ildasm\dotnet-ildasm.csproj

artifacts:
- path: '**\*.nupkg'

deploy:
  - provider: NuGet
    server: 
    api_key:
      secure: Hh52nD8i4YR/X5yRRaqWNchtVaH3/IvAzl9XcGPsrfQI0DnvJB9Odeju0e5yIG4D
    artifact: /.*\.nupkg/
 
skip_commits:
  files: '**/*.md'