version: '{build}' 
configuration:
- Release
platform: Any CPU 
image: Visual Studio 2017

environment: 
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0") 

install:
- choco install gitversion.portable -y

before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
- build.cmd -c Release

test_script:
- dotnet test src\dotnet-ildasm.tests\dotnet-ildasm.tests.csproj
- run-cross-checks.cmd

after_test:
- dotnet pack src\dotnet-ildasm\dotnet-ildasm.csproj

artifacts:
- path: '**\*.nupkg'


deploy:
  - provider: NuGet
    name: Unstable releases
    server: https://www.myget.org/F/pjbgf/api/v2/package
    api_key:
      secure: jnSpdhFvTcq+3qoOA1HJmGoo6hwyFJdU/ryAYF6umUYMzpzq6bjvs/oe+Wrsob6m
    artifact: /.*\.nupkg/
    skip_symbols: true
    prerelease: true
    on:
      branch: /feature.*/

  - provider: NuGet
    name: Preview releases
    server: 
    api_key:
      secure: /ndfcg+DPzrEghZNXPELdI/mGYbglaBEZy4ZGpCyJ+1rYqHF1csEDDhH3sYteOJg
    artifact: /.*\.nupkg/
    skip_symbols: true
    prerelease: true
    on:
      branch: /release.*/
      
  - provider: NuGet
    name: Stable releases
    server: 
    api_key:
      secure: sEuDj+L3zfAaK4bBIl2X0HU+zM7OjklVP9sv1rK6+sLTMFwlvzyAe9/ke4Mws30z
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      secure: RG/QNz1gYC7yCa+7vaTNGw+V4oB+/PynMDGryqWz+Tzf7pAEMyiXfQH5h6m3/VdL
    draft: true
    skip_symbols: false
    on:
      branch: master

skip_commits:
  files: '**/*.md'
